// Curated Bangladesh parts & servicing costs per research model. These are NOT
// scraped — classifieds don't carry parts prices — they're compiled from local
// independent-workshop averages (parts + labour, BDT). Keyed by ResearchModel
// slug. Shared by the seed and the scraper/backfill script so there's one source.
//
// `intervalKm` on a routine item lets the UI annualise the cost (at a typical
// 15,000 km/year). Items without an interval are one-off reference prices.

export type MaintItem = {
  category: "Routine service" | "Wear & tear" | "Major job";
  name: string;
  priceBdt: number;
  intervalKm?: number;
  note?: string;
};

export const MAINTENANCE: Record<string, MaintItem[]> = {
  harrier: [
    { category: "Routine service", name: "Engine oil + filter", priceBdt: 6500, intervalKm: 8000 },
    { category: "Routine service", name: "Air filter", priceBdt: 1800, intervalKm: 20000 },
    { category: "Routine service", name: "Cabin / AC filter", priceBdt: 1200, intervalKm: 15000 },
    { category: "Routine service", name: "CVT fluid change", priceBdt: 9000, intervalKm: 40000 },
    { category: "Routine service", name: "Wheel alignment & balancing", priceBdt: 1200, intervalKm: 10000 },
    { category: "Wear & tear", name: "Brake pads — front set", priceBdt: 6500, intervalKm: 40000 },
    { category: "Wear & tear", name: "Brake pads — rear set", priceBdt: 5000, intervalKm: 60000 },
    { category: "Wear & tear", name: "Tyre (each, 225/60R18)", priceBdt: 16000, intervalKm: 50000 },
    { category: "Wear & tear", name: "Battery (12V)", priceBdt: 12000, intervalKm: 60000, note: "≈ 3–4 years" },
    { category: "Wear & tear", name: "Spark plugs (petrol set)", priceBdt: 5000, intervalKm: 100000 },
    { category: "Major job", name: "Timing chain service", priceBdt: 30000 },
    { category: "Major job", name: "Shock absorber (each)", priceBdt: 9000 },
    { category: "Major job", name: "AC compressor", priceBdt: 45000 },
    { category: "Major job", name: "Hybrid drive battery", priceBdt: 220000, note: "hybrid only — reconditioned units far cheaper" },
  ],
  vezel: [
    { category: "Routine service", name: "Engine oil + filter", priceBdt: 5000, intervalKm: 8000 },
    { category: "Routine service", name: "Air filter", priceBdt: 1400, intervalKm: 20000 },
    { category: "Routine service", name: "Cabin / AC filter", priceBdt: 1000, intervalKm: 15000 },
    { category: "Routine service", name: "CVT fluid change", priceBdt: 7500, intervalKm: 40000 },
    { category: "Routine service", name: "Wheel alignment & balancing", priceBdt: 1000, intervalKm: 10000 },
    { category: "Wear & tear", name: "Brake pads — front set", priceBdt: 4500, intervalKm: 40000 },
    { category: "Wear & tear", name: "Brake pads — rear set", priceBdt: 3500, intervalKm: 60000 },
    { category: "Wear & tear", name: "Tyre (each, 215/60R16)", priceBdt: 11000, intervalKm: 50000 },
    { category: "Wear & tear", name: "Battery (12V)", priceBdt: 9000, intervalKm: 60000, note: "≈ 3–4 years" },
    { category: "Wear & tear", name: "Spark plugs (set)", priceBdt: 4000, intervalKm: 100000 },
    { category: "Major job", name: "Timing chain service", priceBdt: 22000 },
    { category: "Major job", name: "Shock absorber (each)", priceBdt: 6500 },
    { category: "Major job", name: "AC compressor", priceBdt: 35000 },
    { category: "Major job", name: "Hybrid IPU / drive battery", priceBdt: 160000, note: "reconditioned units common in BD" },
  ],
  cx5: [
    { category: "Routine service", name: "Engine oil + filter", priceBdt: 6000, intervalKm: 8000 },
    { category: "Routine service", name: "Air filter", priceBdt: 2000, intervalKm: 20000 },
    { category: "Routine service", name: "Cabin / AC filter", priceBdt: 1500, intervalKm: 15000 },
    { category: "Routine service", name: "Auto transmission fluid", priceBdt: 9500, intervalKm: 60000 },
    { category: "Routine service", name: "Wheel alignment & balancing", priceBdt: 1200, intervalKm: 10000 },
    { category: "Wear & tear", name: "Brake pads — front set", priceBdt: 7000, intervalKm: 40000, note: "Mazda parts pricier / less common" },
    { category: "Wear & tear", name: "Brake pads — rear set", priceBdt: 5500, intervalKm: 60000 },
    { category: "Wear & tear", name: "Tyre (each, 225/65R17)", priceBdt: 15000, intervalKm: 50000 },
    { category: "Wear & tear", name: "Battery (12V)", priceBdt: 14000, intervalKm: 60000 },
    { category: "Wear & tear", name: "Spark plugs (SkyActiv set)", priceBdt: 6000, intervalKm: 100000 },
    { category: "Major job", name: "Timing chain service", priceBdt: 32000 },
    { category: "Major job", name: "Shock absorber (each)", priceBdt: 10000 },
    { category: "Major job", name: "AC compressor", priceBdt: 50000 },
    { category: "Major job", name: "Mazda Connect infotainment repair", priceBdt: 25000, note: "known failure point" },
  ],
  premio: [
    { category: "Routine service", name: "Engine oil + filter", priceBdt: 4000, intervalKm: 10000 },
    { category: "Routine service", name: "Air filter", priceBdt: 1000, intervalKm: 20000 },
    { category: "Routine service", name: "Cabin / AC filter", priceBdt: 900, intervalKm: 15000 },
    { category: "Routine service", name: "ATF / CVT fluid", priceBdt: 6000, intervalKm: 40000 },
    { category: "Routine service", name: "Wheel alignment & balancing", priceBdt: 900, intervalKm: 10000 },
    { category: "Wear & tear", name: "Brake pads — front set", priceBdt: 3000, intervalKm: 40000 },
    { category: "Wear & tear", name: "Brake shoes — rear", priceBdt: 2500, intervalKm: 60000 },
    { category: "Wear & tear", name: "Tyre (each, 195/65R15)", priceBdt: 8500, intervalKm: 50000 },
    { category: "Wear & tear", name: "Battery (12V)", priceBdt: 8000, intervalKm: 60000 },
    { category: "Wear & tear", name: "Spark plugs (set)", priceBdt: 2500, intervalKm: 100000 },
    { category: "Major job", name: "Timing chain service", priceBdt: 18000 },
    { category: "Major job", name: "Shock absorber (each)", priceBdt: 5500 },
    { category: "Major job", name: "AC compressor", priceBdt: 28000 },
    { category: "Major job", name: "Power window regulator", priceBdt: 6000, note: "common wear item" },
  ],
  axio: [
    { category: "Routine service", name: "Engine oil + filter", priceBdt: 4200, intervalKm: 8000 },
    { category: "Routine service", name: "Air filter", priceBdt: 1000, intervalKm: 20000 },
    { category: "Routine service", name: "Cabin / AC filter", priceBdt: 900, intervalKm: 15000 },
    { category: "Routine service", name: "CVT fluid change", priceBdt: 6000, intervalKm: 40000 },
    { category: "Routine service", name: "Wheel alignment & balancing", priceBdt: 900, intervalKm: 10000 },
    { category: "Wear & tear", name: "Brake pads — front set", priceBdt: 3200, intervalKm: 40000 },
    { category: "Wear & tear", name: "Brake pads — rear set", priceBdt: 2600, intervalKm: 60000 },
    { category: "Wear & tear", name: "Tyre (each, 185/60R15)", priceBdt: 8000, intervalKm: 50000 },
    { category: "Wear & tear", name: "Battery (12V)", priceBdt: 8000, intervalKm: 60000 },
    { category: "Wear & tear", name: "Spark plugs (set)", priceBdt: 2500, intervalKm: 100000 },
    { category: "Major job", name: "Timing chain service", priceBdt: 18000 },
    { category: "Major job", name: "Shock absorber (each)", priceBdt: 5500 },
    { category: "Major job", name: "AC compressor", priceBdt: 28000 },
    { category: "Major job", name: "Hybrid drive battery", priceBdt: 130000, note: "hybrid only — reconditioned far cheaper" },
  ],
  aqua: [
    { category: "Routine service", name: "Engine oil + filter", priceBdt: 4000, intervalKm: 8000 },
    { category: "Routine service", name: "Air filter", priceBdt: 1000, intervalKm: 20000 },
    { category: "Routine service", name: "Cabin / AC filter", priceBdt: 900, intervalKm: 15000 },
    { category: "Routine service", name: "Hybrid inverter coolant", priceBdt: 4500, intervalKm: 60000 },
    { category: "Routine service", name: "Wheel alignment & balancing", priceBdt: 900, intervalKm: 10000 },
    { category: "Wear & tear", name: "Brake pads — front set", priceBdt: 3000, intervalKm: 40000 },
    { category: "Wear & tear", name: "Brake pads — rear set", priceBdt: 2500, intervalKm: 60000 },
    { category: "Wear & tear", name: "Tyre (each, 175/65R15)", priceBdt: 7500, intervalKm: 50000 },
    { category: "Wear & tear", name: "Battery (12V auxiliary)", priceBdt: 7000, intervalKm: 60000 },
    { category: "Wear & tear", name: "Spark plugs (set)", priceBdt: 2500, intervalKm: 100000 },
    { category: "Major job", name: "Timing chain service", priceBdt: 16000 },
    { category: "Major job", name: "Shock absorber (each)", priceBdt: 5000 },
    { category: "Major job", name: "AC compressor", priceBdt: 26000 },
    { category: "Major job", name: "Hybrid drive battery", priceBdt: 120000, note: "reconditioned units common in BD" },
  ],
  "corolla-cross": [
    { category: "Routine service", name: "Engine oil + filter", priceBdt: 6500, intervalKm: 10000 },
    { category: "Routine service", name: "Air filter", priceBdt: 2000, intervalKm: 20000 },
    { category: "Routine service", name: "Cabin / AC filter", priceBdt: 1500, intervalKm: 15000 },
    { category: "Routine service", name: "CVT fluid change", priceBdt: 9000, intervalKm: 40000 },
    { category: "Routine service", name: "Wheel alignment & balancing", priceBdt: 1200, intervalKm: 10000 },
    { category: "Wear & tear", name: "Brake pads — front set", priceBdt: 6500, intervalKm: 40000 },
    { category: "Wear & tear", name: "Brake pads — rear set", priceBdt: 5000, intervalKm: 60000 },
    { category: "Wear & tear", name: "Tyre (each, 225/50R18)", priceBdt: 15000, intervalKm: 50000 },
    { category: "Wear & tear", name: "Battery (12V)", priceBdt: 13000, intervalKm: 60000 },
    { category: "Wear & tear", name: "Spark plugs (set)", priceBdt: 5000, intervalKm: 100000 },
    { category: "Major job", name: "Timing chain service", priceBdt: 30000 },
    { category: "Major job", name: "Shock absorber (each)", priceBdt: 9500 },
    { category: "Major job", name: "AC compressor", priceBdt: 48000 },
    { category: "Major job", name: "Hybrid drive battery", priceBdt: 200000, note: "hybrid only" },
  ],
  noah: [
    { category: "Routine service", name: "Engine oil + filter", priceBdt: 6000, intervalKm: 8000 },
    { category: "Routine service", name: "Air filter", priceBdt: 1800, intervalKm: 20000 },
    { category: "Routine service", name: "Cabin / AC filter", priceBdt: 1300, intervalKm: 15000 },
    { category: "Routine service", name: "CVT fluid change", priceBdt: 8500, intervalKm: 40000 },
    { category: "Routine service", name: "Wheel alignment & balancing", priceBdt: 1200, intervalKm: 10000 },
    { category: "Wear & tear", name: "Brake pads — front set", priceBdt: 6000, intervalKm: 40000 },
    { category: "Wear & tear", name: "Brake pads — rear set", priceBdt: 4800, intervalKm: 60000 },
    { category: "Wear & tear", name: "Tyre (each, 205/60R16)", priceBdt: 12000, intervalKm: 50000 },
    { category: "Wear & tear", name: "Battery (12V)", priceBdt: 12000, intervalKm: 60000 },
    { category: "Major job", name: "Sliding-door motor", priceBdt: 15000, note: "common wear item" },
    { category: "Major job", name: "Timing chain service", priceBdt: 26000 },
    { category: "Major job", name: "Shock absorber (each)", priceBdt: 8500 },
    { category: "Major job", name: "AC compressor", priceBdt: 42000 },
    { category: "Major job", name: "Hybrid drive battery", priceBdt: 180000, note: "hybrid only" },
  ],
  fit: [
    { category: "Routine service", name: "Engine oil + filter", priceBdt: 4500, intervalKm: 8000 },
    { category: "Routine service", name: "Air filter", priceBdt: 1200, intervalKm: 20000 },
    { category: "Routine service", name: "Cabin / AC filter", priceBdt: 1000, intervalKm: 15000 },
    { category: "Routine service", name: "CVT fluid change", priceBdt: 7000, intervalKm: 40000 },
    { category: "Routine service", name: "Wheel alignment & balancing", priceBdt: 1000, intervalKm: 10000 },
    { category: "Wear & tear", name: "Brake pads — front set", priceBdt: 4000, intervalKm: 40000 },
    { category: "Wear & tear", name: "Brake pads — rear set", priceBdt: 3200, intervalKm: 60000 },
    { category: "Wear & tear", name: "Tyre (each, 185/60R15)", priceBdt: 8500, intervalKm: 50000 },
    { category: "Wear & tear", name: "Battery (12V)", priceBdt: 8500, intervalKm: 60000 },
    { category: "Wear & tear", name: "Spark plugs (set)", priceBdt: 3500, intervalKm: 100000 },
    { category: "Major job", name: "Timing chain service", priceBdt: 20000 },
    { category: "Major job", name: "Shock absorber (each)", priceBdt: 6000 },
    { category: "Major job", name: "AC compressor", priceBdt: 32000 },
    { category: "Major job", name: "i-DCD hybrid clutch / drive battery", priceBdt: 90000, note: "hybrid units only" },
  ],
  grace: [
    { category: "Routine service", name: "Engine oil + filter", priceBdt: 4800, intervalKm: 8000 },
    { category: "Routine service", name: "Air filter", priceBdt: 1200, intervalKm: 20000 },
    { category: "Routine service", name: "Cabin / AC filter", priceBdt: 1000, intervalKm: 15000 },
    { category: "Routine service", name: "Hybrid transmission fluid", priceBdt: 6500, intervalKm: 40000 },
    { category: "Routine service", name: "Wheel alignment & balancing", priceBdt: 1000, intervalKm: 10000 },
    { category: "Wear & tear", name: "Brake pads — front set", priceBdt: 4200, intervalKm: 40000 },
    { category: "Wear & tear", name: "Brake pads — rear set", priceBdt: 3300, intervalKm: 60000 },
    { category: "Wear & tear", name: "Tyre (each, 185/60R15)", priceBdt: 9000, intervalKm: 50000 },
    { category: "Wear & tear", name: "Battery (12V)", priceBdt: 8500, intervalKm: 60000 },
    { category: "Wear & tear", name: "Spark plugs (set)", priceBdt: 3500, intervalKm: 100000 },
    { category: "Major job", name: "Timing chain service", priceBdt: 20000 },
    { category: "Major job", name: "Shock absorber (each)", priceBdt: 6000 },
    { category: "Major job", name: "AC compressor", priceBdt: 32000 },
    { category: "Major job", name: "Hybrid clutch pack", priceBdt: 85000 },
  ],
  "x-trail": [
    { category: "Routine service", name: "Engine oil + filter", priceBdt: 6000, intervalKm: 8000 },
    { category: "Routine service", name: "Air filter", priceBdt: 2000, intervalKm: 20000 },
    { category: "Routine service", name: "Cabin / AC filter", priceBdt: 1400, intervalKm: 15000 },
    { category: "Routine service", name: "CVT fluid change", priceBdt: 9500, intervalKm: 40000 },
    { category: "Routine service", name: "Wheel alignment & balancing", priceBdt: 1200, intervalKm: 10000 },
    { category: "Wear & tear", name: "Brake pads — front set", priceBdt: 6500, intervalKm: 40000 },
    { category: "Wear & tear", name: "Brake pads — rear set", priceBdt: 5000, intervalKm: 60000 },
    { category: "Wear & tear", name: "Tyre (each, 225/65R17)", priceBdt: 14000, intervalKm: 50000 },
    { category: "Wear & tear", name: "Battery (12V)", priceBdt: 13000, intervalKm: 60000 },
    { category: "Wear & tear", name: "Spark plugs (set)", priceBdt: 5000, intervalKm: 100000 },
    { category: "Major job", name: "CVT overhaul", priceBdt: 55000, note: "known weak point on hills" },
    { category: "Major job", name: "Shock absorber (each)", priceBdt: 9000 },
    { category: "Major job", name: "AC compressor", priceBdt: 48000 },
    { category: "Major job", name: "Hybrid drive battery", priceBdt: 170000, note: "hybrid only" },
  ],
  note: [
    { category: "Routine service", name: "Engine oil + filter", priceBdt: 4500, intervalKm: 8000 },
    { category: "Routine service", name: "Air filter", priceBdt: 1200, intervalKm: 20000 },
    { category: "Routine service", name: "Cabin / AC filter", priceBdt: 1000, intervalKm: 15000 },
    { category: "Routine service", name: "Brake fluid flush", priceBdt: 1800, intervalKm: 40000 },
    { category: "Routine service", name: "Wheel alignment & balancing", priceBdt: 1000, intervalKm: 10000 },
    { category: "Wear & tear", name: "Brake pads — front set", priceBdt: 3800, intervalKm: 40000 },
    { category: "Wear & tear", name: "Brake pads — rear set", priceBdt: 3000, intervalKm: 60000 },
    { category: "Wear & tear", name: "Tyre (each, 185/65R15)", priceBdt: 8000, intervalKm: 50000 },
    { category: "Wear & tear", name: "Battery (12V)", priceBdt: 8500, intervalKm: 60000 },
    { category: "Wear & tear", name: "Spark plugs (set)", priceBdt: 3000, intervalKm: 100000 },
    { category: "Major job", name: "e-POWER inverter service", priceBdt: 40000, note: "e-POWER units only" },
    { category: "Major job", name: "Shock absorber (each)", priceBdt: 5500 },
    { category: "Major job", name: "AC compressor", priceBdt: 30000 },
    { category: "Major job", name: "e-POWER drive battery", priceBdt: 110000, note: "e-POWER units only" },
  ],
  swift: [
    { category: "Routine service", name: "Engine oil + filter", priceBdt: 3500, intervalKm: 10000 },
    { category: "Routine service", name: "Air filter", priceBdt: 900, intervalKm: 20000 },
    { category: "Routine service", name: "Cabin / AC filter", priceBdt: 800, intervalKm: 15000 },
    { category: "Routine service", name: "ATF / CVT fluid", priceBdt: 5500, intervalKm: 40000 },
    { category: "Routine service", name: "Wheel alignment & balancing", priceBdt: 800, intervalKm: 10000 },
    { category: "Wear & tear", name: "Brake pads — front set", priceBdt: 2800, intervalKm: 40000 },
    { category: "Wear & tear", name: "Brake shoes — rear", priceBdt: 2200, intervalKm: 60000 },
    { category: "Wear & tear", name: "Tyre (each, 185/55R16)", priceBdt: 7000, intervalKm: 50000 },
    { category: "Wear & tear", name: "Battery (12V)", priceBdt: 7000, intervalKm: 60000 },
    { category: "Wear & tear", name: "Spark plugs (set)", priceBdt: 2200, intervalKm: 100000 },
    { category: "Major job", name: "Timing chain service", priceBdt: 15000 },
    { category: "Major job", name: "Shock absorber (each)", priceBdt: 4800 },
    { category: "Major job", name: "AC compressor", priceBdt: 24000 },
    { category: "Major job", name: "Clutch kit", priceBdt: 12000, note: "manual units" },
  ],
  outlander: [
    { category: "Routine service", name: "Engine oil + filter", priceBdt: 6500, intervalKm: 8000 },
    { category: "Routine service", name: "Air filter", priceBdt: 2200, intervalKm: 20000 },
    { category: "Routine service", name: "Cabin / AC filter", priceBdt: 1600, intervalKm: 15000 },
    { category: "Routine service", name: "CVT fluid change", priceBdt: 10000, intervalKm: 40000 },
    { category: "Routine service", name: "Wheel alignment & balancing", priceBdt: 1300, intervalKm: 10000 },
    { category: "Wear & tear", name: "Brake pads — front set", priceBdt: 7000, intervalKm: 40000 },
    { category: "Wear & tear", name: "Brake pads — rear set", priceBdt: 5500, intervalKm: 60000 },
    { category: "Wear & tear", name: "Tyre (each, 225/55R18)", priceBdt: 15000, intervalKm: 50000 },
    { category: "Wear & tear", name: "Battery (12V)", priceBdt: 14000, intervalKm: 60000 },
    { category: "Wear & tear", name: "Spark plugs (set)", priceBdt: 5500, intervalKm: 100000 },
    { category: "Major job", name: "Timing chain service", priceBdt: 32000 },
    { category: "Major job", name: "Shock absorber (each)", priceBdt: 10000 },
    { category: "Major job", name: "AC compressor", priceBdt: 50000 },
    { category: "Major job", name: "PHEV drive battery", priceBdt: 250000, note: "plug-in units only" },
  ],
};
